apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::867156520614:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
          - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::867156520614:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WW07H6O4UIMH
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-20T18:46:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1673"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3e3c8154-247c-4909-a625-aed39d02536b
