apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::867156520614:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::867156520614:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-31F2QPMXJZIX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-19T01:45:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1432"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 64c5b93b-8421-4965-af59-26c51d20ff2a
